# node list, https://atomscan.com/directory/celestia
endPoint = "https://fullnode.mainnet.sui.io:443"
# 助记词
phrase = ""
#默认使用第一个前面挖矿，对应ok等其他钱包的账号索引
minerIndex = 0
#铭文主体
[posy]
#根据官方参数配置
amt = 100
tick = "ShiB"
p = "suirc-20"
